### ISSUE TITLE
TweenMachine Broken in Maya 2020

### ISSUE THREAD

**Issue by ghost** [boredstiff/tweenMachine#29]
- Maya 2020
- Failed to install TweenMachine when adding them to the correct files and executing the python / Mel script in the script editor.

**Comment by joseketsia** [comment]
I'm having the same problem

**Comment by boredstiff** [comment]
I'm sorry, but this is not enough information for me to be able to help. What's the error? Did you follow the instructions saying to use the files in the releases instead of using what was in master?

Additionally, I don't have a license for Maya past 2018 which will also lapse this year, and will not be purchasing a license for newer versions so I am unable to provide any support. I apologize.

**Comment by ghost** [comment]
Hello there,

There is no error. The plugin simply won't load into Maya 2020. I used the master as well as try to use the files in the releases. If it helps I can give you access to my student lisence, or I can try to provide a video demonstrating the problem? Let me know :)

**Comment by joseketsia** [comment]
Ok.
I checked and I actually use MAYA 2019.2. But if could try using your
student license that would be really helpful.

**Comment by boredstiff** [comment]
_It is against the terms of your license agreement to allow someone else to use it. Do not give your license to anyone._

It says in the instructions to not use master: 

`Animators: Do not copy the file listed directly above, as tweenMachine is in active development and will be for the next few weeks. Instead, go to the Releases tab above the files, and download version 3.0.0.
`

Wherever I last left off, what is in master was incomplete. Only the releases would work.

**Comment by joseketsia** [comment]
Alright so I should download the 3.0.0 release instead?

**Comment by boredstiff** [comment]
Yes

**Comment by joseketsia** [comment]
This time it worked. Thanks for the help!

**Comment by ghost** [comment]
I'll try this when I'm at home. joseketsia can you explain to me what you did?

At the moment I'm using the animtools tweener and it's painfully slow. :(

**Comment by joseketsia** [comment]
I saw that I was downloading the 1.2.5 version I think so I deleted it and
downloaded and installed the 3.0.0 release instead and it worked fine.

**Comment by ghost** [comment]
Awesome Thank You! :)
